// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVideo struct {
	Title string `json:"title"`
	URL   string `json:"url"`
}

type Video struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	URL   string `json:"url"`
}
